version: '3'
networks:
  default:
    external:
      name: pnu
services:
  explorer.pusan.ac.kr:
    restart: always
    container_name: explorer.pusan.ac.kr
    image: hyperledger/explorer:1.1.4
    environment:
      - DATABASE_HOST=explorerdb.pusan.ac.kr
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWD=adminpw
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    depends_on:
      - explorerdb.pusan.ac.kr
    volumes:
      - /opt/smartm2m/dist/src/asset:/opt/smartm2m/dist/src/asset
      - ../explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - >-
        ../explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../artifacts/crypto-config:/usr/app/asset/pnu/crypto-config
      - ../wallet:/opt/explorer/wallet
    ports:
      - '8080:8080'
  explorerdb.pusan.ac.kr:
    restart: always
    container_name: explorerdb.pusan.ac.kr
    image: hyperledger/explorer-db:1.1.4
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWD=adminpw
