version: '3'
networks:
  default:
    external:
      name: pnu
services:
  orderer2.pusan.ac.kr:
    restart: always
    container_name: orderer2.pusan.ac.kr
    image: docker.io/hyperledger/fabric-orderer:2.2.2
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/orderer
      - FABRIC_LOGGING_SPEC=info
    working_dir: /etc/hyperledger/orderer
    command: orderer
    ports:
      - 9050:7050
    volumes:
      - ../config/orderer.yaml:/etc/hyperledger/orderer/orderer.yaml
      - ../artifacts/block:/etc/hyperledger/orderer/block
      - >-
        ../artifacts/crypto-config/ordererOrganizations/pusan.ac.kr/orderers/orderer2.pusan.ac.kr/msp:/etc/hyperledger/orderer/crypto-config/msp
      - >-
        ../artifacts/crypto-config/ordererOrganizations/pusan.ac.kr/orderers/orderer2.pusan.ac.kr/tls:/etc/hyperledger/orderer/crypto-config/tls
      - >-
        ../artifacts/crypto-config/ordererOrganizations/pusan.ac.kr/tlsca/tlsca.pusan.ac.kr-cert.pem:/etc/hyperledger/orderer/crypto-config/tlsca/tlsca.orderer-cert.pem
      - >-
        ../artifacts/crypto-config/peerOrganizations/management.pusan.ac.kr/tlsca/tlsca.management.pusan.ac.kr-cert.pem:/etc/hyperledger/orderer/crypto-config/tlsca/tlsca.management.pusan.ac.kr-cert.pem
      - >-
        ../artifacts/crypto-config/peerOrganizations/verification-01.pusan.ac.kr/tlsca/tlsca.verification-01.pusan.ac.kr-cert.pem:/etc/hyperledger/orderer/crypto-config/tlsca/tlsca.verification-01.pusan.ac.kr-cert.pem
      - >-
        ../artifacts/crypto-config/peerOrganizations/verification-02.pusan.ac.kr/tlsca/tlsca.verification-02.pusan.ac.kr-cert.pem:/etc/hyperledger/orderer/crypto-config/tlsca/tlsca.verification-02.pusan.ac.kr-cert.pem
      - >-
        ../artifacts/crypto-config/peerOrganizations/trader.pusan.ac.kr/tlsca/tlsca.trader.pusan.ac.kr-cert.pem:/etc/hyperledger/orderer/crypto-config/tlsca/tlsca.trader.pusan.ac.kr-cert.pem
