Profiles:
  dnaProfile:
    Consortium: SmartM2M
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V2_0: true
    Application:
      ACLs:
        _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
        _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
        _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers
        _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Readers
        lscc/ChaincodeExists: /Channel/Application/Readers
        lscc/GetDeploymentSpec: /Channel/Application/Readers
        lscc/GetChaincodeData: /Channel/Application/Readers
        peerOrgDefaultslscc/GetInstantiatedChaincodes: /Channel/Application/Readers
        qscc/GetChainInfo: /Channel/Application/Readers
        qscc/GetBlockByNumber: /Channel/Application/Readers
        qscc/GetBlockByHash: /Channel/Application/Readers
        qscc/GetTransactionByID: /Channel/Application/Readers
        qscc/GetBlockByTxID: /Channel/Application/Readers
        cscc/GetConfigBlock: /Channel/Application/Readers
        cscc/GetChannelConfig: /Channel/Application/Readers
        peer/Propose: /Channel/Application/Writers
        peer/ChaincodeToChaincode: /Channel/Application/Writers
        event/Block: /Channel/Application/Readers
        event/FilteredBlock: /Channel/Application/Readers
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        LifecycleEndorsement:
          Type: ImplicitMeta
          Rule: ANY Endorsement
        Endorsement:
          Type: ImplicitMeta
          Rule: ANY Endorsement
      Capabilities:
        V2_0: true
      Organizations:
        - Name: managementMSP
          ID: managementMSP
          MSPDir: crypto-config/peerOrganizations/management.pusan.ac.kr/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR("managementMSP.member")
            Writers:
              Type: Signature
              Rule: OR("managementMSP.member")
            Admins:
              Type: Signature
              Rule: OR("managementMSP.admin")
            Endorsement:
              Type: Signature
              Rule: OR("managementMSP.peer")
          OrdererEndpoints:
            - orderer0.pusan.ac.kr:7050
            - orderer1.pusan.ac.kr:7050
            - orderer2.pusan.ac.kr:7050
          AnchorPeers:
            - Host: peer0.management.pusan.ac.kr
              Port: 7051
        - Name: verification-01MSP
          ID: verification-01MSP
          MSPDir: crypto-config/peerOrganizations/verification-01.pusan.ac.kr/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR("verification-01MSP.member")
            Writers:
              Type: Signature
              Rule: OR("verification-01MSP.member")
            Admins:
              Type: Signature
              Rule: OR("verification-01MSP.admin")
            Endorsement:
              Type: Signature
              Rule: OR("verification-01MSP.peer")
          OrdererEndpoints:
            - orderer0.pusan.ac.kr:7050
            - orderer1.pusan.ac.kr:7050
            - orderer2.pusan.ac.kr:7050
          AnchorPeers:
            - Host: peer0.verification-01.pusan.ac.kr
              Port: 7051
        - Name: verification-02MSP
          ID: verification-02MSP
          MSPDir: crypto-config/peerOrganizations/verification-02.pusan.ac.kr/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR("verification-02MSP.member")
            Writers:
              Type: Signature
              Rule: OR("verification-02MSP.member")
            Admins:
              Type: Signature
              Rule: OR("verification-02MSP.admin")
            Endorsement:
              Type: Signature
              Rule: OR("verification-02MSP.peer")
          OrdererEndpoints:
            - orderer0.pusan.ac.kr:7050
            - orderer1.pusan.ac.kr:7050
            - orderer2.pusan.ac.kr:7050
          AnchorPeers:
            - Host: peer0.verification-02.pusan.ac.kr
              Port: 7051
        - Name: traderMSP
          ID: traderMSP
          MSPDir: crypto-config/peerOrganizations/trader.pusan.ac.kr/msp
          Policies:
            Readers:
              Type: Signature
              Rule: OR("traderMSP.member")
            Writers:
              Type: Signature
              Rule: OR("traderMSP.member")
            Admins:
              Type: Signature
              Rule: OR("traderMSP.admin")
            Endorsement:
              Type: Signature
              Rule: OR("traderMSP.peer")
          OrdererEndpoints:
            - orderer0.pusan.ac.kr:7050
            - orderer1.pusan.ac.kr:7050
            - orderer2.pusan.ac.kr:7050
          AnchorPeers:
            - Host: peer0.trader.pusan.ac.kr
              Port: 7051
